version: "3.9"

services:
    mysql:
        image: mysql:8.1.0
        restart: "always"
        ports:
            - "3306:3306"
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./Database/init_db/:/docker-entrypoint-initdb.d/

    facadeserver:
        image: petoo/facadeserver:1.2
        restart: "always"
        ports:
            - "8080:8080"
        container_name: facadeserver

    dbserver:
        image: petoo/databaseserver:1.2
        restart: "always"
        ports:
            - "8081:8081"
        depends_on:
            - mysql
        container_name: dbserver

    conversionserver:
        image: petoo/conversionserver:1.2
        restart: "always"
        ports:
            - "8082:8082"
        container_name: conversionserver
