version: "3.9"

networks:
    scratchnow-api-net:
        driver: bridge

services:
    mysql:
        image: mysql:8.1.0
        restart: "always"
        ports:
            - "3306:3306"
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: Asia/Seoul
        volumes:
            - ./mysql/:/var/lib/mysql

    facadeserver:
        image: mysql:8.1.0
        restart: "always"
        ports:
            - "3306:3306"
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: Asia/Seoul
        volumes:
            - ./mysql/:/var/lib/mysql
